/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package2;

/**
 *
 * @author Jefferson
 */
public class tempConversion extends javax.swing.JFrame {

    /**
     * Creates new form tempConversion
     */
    public tempConversion() {
        super("Temp Converter");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempHeader = new javax.swing.JLabel();
        tempInput = new javax.swing.JTextField();
        celsiusOutput = new javax.swing.JLabel();
        enterFahrenhiet = new javax.swing.JLabel();
        tempOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(330, 100));
        setPreferredSize(new java.awt.Dimension(350, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tempHeader.setText("Fahrenheit to Celsius Converter");
        getContentPane().add(tempHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tempInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tempInputKeyReleased(evt);
            }
        });
        getContentPane().add(tempInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 30));

        celsiusOutput.setText("Celsius Temp:");
        getContentPane().add(celsiusOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 90, 30));

        enterFahrenhiet.setText("Enter Fahrenheit Temperature:");
        getContentPane().add(enterFahrenhiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        tempOutput.setText("***");
        getContentPane().add(tempOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempInputKeyReleased
        double fahrenheit = Double.parseDouble(tempInput.getText()); // Gets teh user input for fahrenhiet ans saves it as double variable
        double celsius = (fahrenheit - 32)*5/9; // Variable for temperature conversion from fahrenheit to celsius 
        tempOutput.setText((Double.toString((Math.round((celsius)))))); // Sets the tempOutput label to display the converted temperature
    }//GEN-LAST:event_tempInputKeyReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tempConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tempConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tempConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tempConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tempConversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celsiusOutput;
    private javax.swing.JLabel enterFahrenhiet;
    private javax.swing.JLabel tempHeader;
    private javax.swing.JTextField tempInput;
    private javax.swing.JLabel tempOutput;
    // End of variables declaration//GEN-END:variables
}
